MODEL:
  SID_APPROACH: "freq_restoration"
  TYPE: vit
  NAME: finetune
  DROP_PATH_RATE: 0.1
  NUM_CLASSES: 2
  REQUIRED_NORMALIZATION: "positive_0_1"
  RESOLUTION_MODE: "arbitrary"
  FEATURE_EXTRACTION_BATCH: 400
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    INIT_VALUES: None
    USE_APE: True
    USE_RPB: False
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: True
    USE_INTERMEDIATE_LAYERS: True
    PROJECTION_DIM: 1024
    PROJECTION_LAYERS: 2
    PATCH_PROJECTION: True
    PATCH_PROJECTION_PER_FEATURE: True
    INTERMEDIATE_LAYERS: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  FRE:
    MASKING_RADIUS: 20
    PROJECTOR_LAST_LAYER_ACTIVATION_TYPE: None
    ORIGINAL_IMAGE_FEATURES_BRANCH: True
  CLS_HEAD:
    MLP_RATIO: 3
  PATCH_VIT:
    MINIMUM_PATCHES: 4
DATA:
  DATASET: csv_sid
  IMG_SIZE: 224
  NUM_WORKERS: 8
  AUGMENTED_VIEWS: 4
  TEST_PREFETCH_FACTOR: 1
AUG:
  COLOR_JITTER: 0.
TRAIN:
  EPOCHS: 35
  WARMUP_EPOCHS: 5
  BASE_LR: 5e-4
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.8
  CLIP_GRAD: None
  LOSS: "bce"
TEST:
  ORIGINAL_RESOLUTION: True
PRINT_FREQ: 100
SAVE_FREQ: 10
